export type Product = { id: string; name: string; description: string; category: string; price_tzs: number; old_price_tzs?: number; image_url: string; sizes: string[]; colors: string[]; in_stock: boolean; rating: number; reviews: number; badge?: string; seller: string };

export const PRODUCTS: Product[] = [
  { id: "linen-shirt", name: "Men's Premium Linen Shirt", description: "Breathable long-sleeve linen shirt for work, weekends and coastal weather.", category: "Men", price_tzs: 68000, old_price_tzs: 85000, image_url: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=900&q=85", sizes: ["S", "M", "L", "XL", "XXL"], colors: ["White", "Sky Blue", "Sand"], in_stock: true, rating: 4.8, reviews: 126, badge: "Bestseller", seller: "Mlimani Fashion" },
  { id: "satin-dress", name: "Satin Evening Dress", description: "Elegant full-length dress with a flattering drape and soft satin finish.", category: "Women", price_tzs: 95000, old_price_tzs: 120000, image_url: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=900&q=85", sizes: ["XS", "S", "M", "L", "XL"], colors: ["Emerald", "Black", "Wine"], in_stock: true, rating: 4.7, reviews: 89, badge: "20% off", seller: "Nuru Studio" },
  { id: "leather-sandals", name: "Handmade Leather Sandals", description: "Durable genuine-leather sandals, hand-finished in Tanzania for daily comfort.", category: "Shoes", price_tzs: 45000, image_url: "https://images.unsplash.com/photo-1603487742131-4160ec999306?auto=format&fit=crop&w=900&q=85", sizes: ["36", "37", "38", "39", "40", "41", "42", "43", "44"], colors: ["Tan", "Dark Brown", "Black"], in_stock: true, rating: 4.9, reviews: 214, badge: "Made locally", seller: "Kariakoo Leather Co." },
  { id: "street-sneakers", name: "Urban Street Sneakers", description: "Lightweight everyday sneakers with a cushioned sole and clean profile.", category: "Shoes", price_tzs: 78000, old_price_tzs: 92000, image_url: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=85", sizes: ["38", "39", "40", "41", "42", "43", "44"], colors: ["Red", "White", "Black"], in_stock: true, rating: 4.6, reviews: 173, badge: "Trending", seller: "City Kicks TZ" },
  { id: "kids-set", name: "Kids Cotton Weekend Set", description: "Soft two-piece cotton set made for active days, play and family outings.", category: "Kids", price_tzs: 38000, image_url: "https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?auto=format&fit=crop&w=900&q=85", sizes: ["2–3 yrs", "4–5 yrs", "6–7 yrs", "8–9 yrs", "10–11 yrs"], colors: ["Mustard", "Navy", "Mint"], in_stock: true, rating: 4.8, reviews: 67, badge: "New", seller: "Little Stars" },
  { id: "office-blazer", name: "Women's Tailored Blazer", description: "Sharp single-breasted blazer that moves easily from office to evening.", category: "Women", price_tzs: 110000, image_url: "https://images.unsplash.com/photo-1591369822096-ffd140ec948f?auto=format&fit=crop&w=900&q=85", sizes: ["S", "M", "L", "XL"], colors: ["Camel", "Black", "Ivory"], in_stock: true, rating: 4.7, reviews: 54, seller: "Dar Mode" },
  { id: "weekend-polo", name: "Classic Piqué Polo", description: "Smart cotton polo with a structured collar, built for Tanzania's warm weather.", category: "Men", price_tzs: 42000, image_url: "https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?auto=format&fit=crop&w=900&q=85", sizes: ["S", "M", "L", "XL", "XXL"], colors: ["Navy", "Forest", "White"], in_stock: true, rating: 4.5, reviews: 91, seller: "Mlimani Fashion" },
  { id: "woven-tote", name: "Large Woven Market Tote", description: "Roomy structured tote for work, shopping and weekends away.", category: "Accessories", price_tzs: 52000, image_url: "https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&w=900&q=85", sizes: ["One size"], colors: ["Natural", "Black", "Rust"], in_stock: true, rating: 4.9, reviews: 118, badge: "Artisan pick", seller: "Coastal Collective" },
  { id: "hoodie", name: "Essential Heavyweight Hoodie", description: "Premium brushed-cotton hoodie for cool evenings and travel days.", category: "Unisex", price_tzs: 72000, image_url: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=900&q=85", sizes: ["S", "M", "L", "XL", "XXL"], colors: ["Charcoal", "Cream", "Olive"], in_stock: true, rating: 4.8, reviews: 142, badge: "Top rated", seller: "Bongo Basics" },
  { id: "watch", name: "Minimal Steel Watch", description: "Water-resistant everyday watch with a clean dial and adjustable steel strap.", category: "Accessories", price_tzs: 135000, old_price_tzs: 165000, image_url: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=900&q=85", sizes: ["One size"], colors: ["Silver", "Black", "Rose Gold"], in_stock: true, rating: 4.6, reviews: 76, seller: "Saa House" },
];
export const CATEGORIES = ["All", "Women", "Men", "Shoes", "Kids", "Accessories", "Unisex"];
export const TZ_REGIONS = ["Dar es Salaam", "Arusha", "Mwanza", "Dodoma", "Zanzibar", "Kilimanjaro", "Mbeya", "Morogoro", "Tanga", "Iringa", "Kigoma", "Mtwara", "Other region"];
export function formatTzs(amount: number) { return `TSh ${amount.toLocaleString("en-US")}`; }
