import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, BadgeCheck, Clock3, Heart, RotateCcw, ShieldCheck, Star, Truck } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { SiteFooter, SiteHeader } from "@/components/SiteHeader";
import { useWishlist } from "@/components/WishlistProvider";
import { CATEGORIES, PRODUCTS, formatTzs } from "@/lib/shop";
type HomeSearch = { q?: string; category?: string };
export const Route = createFileRoute("/")({ validateSearch: (search: Record<string, unknown>): HomeSearch => ({ q: typeof search.q === "string" ? search.q : undefined, category: typeof search.category === "string" ? search.category : undefined }), head: () => ({ meta: [{ title: "SokoStyle Tanzania | Fashion, shoes & accessories" }, { name: "description", content: "Shop fashion for women, men and kids with delivery and local payments across Tanzania." }] }), component: Home });

export function ProductCard({ product }: { product: (typeof PRODUCTS)[number] }) {
  const wishlist = useWishlist(); const saved = wishlist.has(product.id);
  return <article className="group min-w-0 overflow-hidden rounded-xl border bg-white transition hover:-translate-y-1 hover:shadow-xl"><div className="relative aspect-[4/5] overflow-hidden bg-slate-100"><Link to="/product/$productId" params={{ productId: product.id }} className="block h-full"><img src={product.image_url} alt={product.name} className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/></Link>{product.badge && <span className="pointer-events-none absolute left-3 top-3 rounded bg-rose-600 px-2 py-1 text-[11px] font-bold text-white">{product.badge}</span>}<button onClick={() => { wishlist.toggle(product.id); toast.success(saved ? "Removed from wishlist" : "Saved to wishlist"); }} aria-label={saved ? `Remove ${product.name} from wishlist` : `Save ${product.name} to wishlist`} className={`absolute right-3 top-3 grid h-9 w-9 place-items-center rounded-full bg-white/95 shadow ${saved ? "text-rose-600" : "text-slate-600"}`}><Heart size={19} fill={saved ? "currentColor" : "none"}/></button></div><div className="p-4"><p className="text-xs text-slate-500">{product.seller}</p><Link to="/product/$productId" params={{ productId: product.id }} className="mt-1 line-clamp-2 block min-h-11 text-sm font-semibold leading-5 text-slate-800 hover:text-emerald-700">{product.name}</Link><div className="mt-2 flex items-center gap-1 text-xs"><span className="flex text-amber-400"><Star size={14} fill="currentColor"/></span><b>{product.rating}</b><span className="text-slate-400">({product.reviews})</span></div><div className="mt-3 flex flex-wrap items-baseline gap-2"><b className="text-lg text-slate-950">{formatTzs(product.price_tzs)}</b>{product.old_price_tzs && <s className="text-xs text-slate-400">{formatTzs(product.old_price_tzs)}</s>}</div><p className="mt-2 text-xs font-medium text-emerald-700">In stock · Delivery available</p></div></article>;
}

function Home() {
  const search = Route.useSearch(); const [selectedCategory, setSelectedCategory] = useState<string | null>(null); const category = selectedCategory ?? search.category ?? "All";
  useEffect(() => setSelectedCategory(null), [search.category, search.q]);
  const shown = useMemo(() => PRODUCTS.filter((p) => (category === "All" || category === "Deals" && !!p.old_price_tzs || category === "New" && p.badge === "New" || p.category === category) && (!search.q || `${p.name} ${p.category} ${p.description}`.toLowerCase().includes(search.q.toLowerCase()))), [category, search.q]);
  const title = search.q ? `Results for “${search.q}”` : category === "Deals" ? "Today’s deals" : category === "New" ? "New arrivals" : category === "All" ? "Popular right now" : category;
  const pick = (value: string) => { setSelectedCategory(value); document.getElementById("shop")?.scrollIntoView({ behavior: "smooth" }); };
  const showHomepageIntro = category === "All" && !search.q;
  return <div className="min-h-screen bg-[#f5f6f7]"><SiteHeader/><main>
    {showHomepageIntro && <>
    <section className="bg-gradient-to-r from-[#073b35] via-[#0a5c4f] to-[#13836c] text-white"><div className="mx-auto grid max-w-7xl items-center px-5 lg:grid-cols-2"><div className="py-14 lg:py-20"><span className="rounded-full bg-amber-300 px-3 py-1 text-xs font-extrabold uppercase tracking-widest text-slate-950">New season · Tanzania</span><h1 className="mt-5 max-w-xl text-4xl font-black leading-[1.05] tracking-tight sm:text-6xl">Your whole wardrobe,<br/><span className="text-amber-300">one trusted place.</span></h1><p className="mt-5 max-w-lg text-base leading-7 text-emerald-50">Discover dresses, shirts, sneakers, sandals, kids’ wear and accessories from trusted local and international sellers.</p><a href="#shop" className="mt-8 inline-flex items-center gap-2 rounded-lg bg-amber-400 px-6 py-3.5 font-bold text-slate-950 shadow-lg hover:bg-amber-300">Shop the collection <ArrowRight size={19}/></a><div className="mt-8 flex flex-wrap gap-5 text-xs text-emerald-50"><span className="flex items-center gap-2"><BadgeCheck size={18}/>Verified sellers</span><span className="flex items-center gap-2"><ShieldCheck size={18}/>Secure payments</span><span className="flex items-center gap-2"><Truck size={18}/>Countrywide delivery</span></div></div><div className="relative hidden h-[430px] lg:block"><img src="https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1200&q=85" alt="Modern fashion store" className="absolute inset-0 h-full w-full object-cover [mask-image:linear-gradient(to_right,transparent,black_20%)]"/><button onClick={() => pick("Deals")} className="absolute bottom-8 right-4 rounded-xl bg-white p-4 text-left text-slate-900 shadow-2xl hover:-translate-y-1"><p className="text-xs text-slate-500">Shop today’s deals</p><b className="text-xl">Save up to 20%</b></button></div></div></section>
    <section className="mx-auto -mt-1 grid max-w-7xl grid-cols-2 border-b bg-white sm:grid-cols-4"><button onClick={() => toast.info("Enter your region at checkout to see your delivery estimate.")} className="flex gap-3 border-r p-4 text-left hover:bg-slate-50"><Truck className="text-emerald-700"/><span className="text-xs"><b className="block">Fast delivery</b>Dar & major cities</span></button><button onClick={() => toast.info("Payments are encrypted and confirmed securely.")} className="flex gap-3 border-r p-4 text-left hover:bg-slate-50"><ShieldCheck className="text-emerald-700"/><span className="text-xs"><b className="block">Pay securely</b>Mobile money & cards</span></button><button onClick={() => toast.info("Unworn items can be returned within 7 days.")} className="flex gap-3 border-r p-4 text-left hover:bg-slate-50"><RotateCcw className="text-emerald-700"/><span className="text-xs"><b className="block">Easy returns</b>Within 7 days</span></button><a href="mailto:support@sokostyle.co.tz" className="flex gap-3 p-4 text-left hover:bg-slate-50"><Clock3 className="text-emerald-700"/><span className="text-xs"><b className="block">Support</b>Email our team</span></a></section>
    </>}
    <section id="shop" className="mx-auto max-w-7xl scroll-mt-44 px-4 py-10"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-widest text-emerald-700">Explore the marketplace</p><h2 className="mt-1 text-3xl font-black text-slate-950">{title}</h2></div><p className="text-sm text-slate-500">{shown.length} items</p></div><div className="mt-6 flex gap-2 overflow-x-auto pb-2">{CATEGORIES.map((c) => <button key={c} onClick={() => pick(c)} className={`rounded-full border px-5 py-2 text-sm font-semibold ${category === c ? "border-emerald-700 bg-emerald-700 text-white" : "bg-white text-slate-700 hover:border-emerald-600"}`}>{c}</button>)}</div><div className="mt-7 grid grid-cols-2 gap-5 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5">{shown.map((product) => <ProductCard key={product.id} product={product}/>)}</div>{shown.length === 0 && <div className="mt-7 rounded-xl bg-white p-16 text-center"><h3 className="text-xl font-bold">No items found</h3><p className="mt-2 text-sm text-slate-500">Try another search or department.</p><button onClick={() => pick("All")} className="mt-5 rounded-lg bg-emerald-700 px-5 py-2.5 font-bold text-white">Show all products</button></div>}</section>
    <section className="mx-auto max-w-7xl px-4"><div className="grid overflow-hidden rounded-2xl bg-amber-300 md:grid-cols-2"><div className="p-9 sm:p-12"><p className="font-bold uppercase tracking-widest text-emerald-900">Made in Tanzania</p><h2 className="mt-3 text-4xl font-black text-slate-950">Support local makers.<br/>Wear something special.</h2><p className="mt-4 max-w-md text-slate-700">Discover quality pieces from designers, leather workers and independent shops across the country.</p><button onClick={() => pick("Accessories")} className="mt-6 rounded-lg bg-slate-950 px-5 py-3 font-bold text-white">Shop local picks</button></div><img src="https://images.unsplash.com/photo-1558769132-cb1aea458c5e?auto=format&fit=crop&w=1000&q=85" alt="Fashion collection" className="h-80 w-full object-cover md:h-full"/></div></section>
  </main><SiteFooter/></div>;
}
