import { Link, useNavigate } from "@tanstack/react-router";
import { Heart, MapPin, Menu, Search, ShoppingCart, UserRound, X } from "lucide-react";
import { useCart } from "@/components/CartProvider";
import { useWishlist } from "@/components/WishlistProvider";
import { useState, type FormEvent } from "react";
import { toast } from "sonner";

const departments = ["All", "Women", "Men", "Shoes", "Kids", "Accessories", "Unisex"];
export function SiteHeader() {
  const { count } = useCart(); const wishlist = useWishlist(); const navigate = useNavigate();
  const [query, setQuery] = useState(""); const [department, setDepartment] = useState("All"); const [menuOpen, setMenuOpen] = useState(false);
  const search = (event: FormEvent) => { event.preventDefault(); navigate({ to: "/", search: { q: query.trim() || undefined, category: department } }); setMenuOpen(false); };
  const choose = (category: string) => { navigate({ to: "/", search: { category } }); setMenuOpen(false); };
  return <header className="sticky top-0 z-50 shadow-sm">
    <div className="bg-slate-950 px-4 py-2 text-center text-xs text-white"><span className="font-semibold text-amber-300">FREE DELIVERY</span> in Dar es Salaam on orders over TSh 100,000 · Lipa kwa M-Pesa, Airtel Money or Mixx by Yas</div>
    <div className="bg-[#087f5b] text-white"><div className="mx-auto flex max-w-7xl items-center gap-4 px-4 py-3">
      <button onClick={() => setMenuOpen(true)} className="rounded p-1 hover:bg-white/10 md:hidden" aria-label="Open menu"><Menu/></button>
      <Link to="/" className="shrink-0 text-2xl font-black tracking-tight">soko<span className="text-amber-300">style</span><small className="ml-1 text-[9px] font-bold uppercase tracking-widest text-white/70">TZ</small></Link>
      <form onSubmit={search} className="hidden flex-1 overflow-hidden rounded-lg bg-white shadow-inner sm:flex"><select value={department} onChange={(e) => setDepartment(e.target.value)} aria-label="Department" className="border-r bg-slate-100 px-3 text-xs text-slate-600 outline-none">{departments.map((item) => <option key={item}>{item}</option>)}</select><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search clothes, shoes, accessories..." className="min-w-0 flex-1 px-4 py-2.5 text-sm text-slate-900 outline-none"/><button className="bg-amber-400 px-5 text-slate-900 hover:bg-amber-300" aria-label="Search"><Search size={20}/></button></form>
      <button onClick={() => toast.info("Delivery location can be selected during checkout.")} className="ml-auto hidden items-center gap-1 rounded px-2 py-1 text-xs hover:bg-white/10 lg:flex"><MapPin size={19}/><span><span className="block text-white/70">Deliver to</span><b>Dar es Salaam</b></span></button>
      <button onClick={() => toast.info("Account sign-in is coming soon. You can shop and check out as a guest.")} className="hidden items-center gap-1 rounded px-2 py-1 hover:bg-white/10 md:flex"><UserRound size={22}/><span className="text-left text-xs"><span className="block text-white/70">Hello, guest</span><b>Account</b></span></button>
      <Link to="/wishlist" className="relative hidden rounded p-1 hover:bg-white/10 lg:block" aria-label={`Wishlist with ${wishlist.ids.length} items`}><Heart size={22}/>{wishlist.ids.length > 0 && <span className="absolute -right-2 -top-2 grid h-4 min-w-4 place-items-center rounded-full bg-amber-400 px-1 text-[10px] text-slate-950">{wishlist.ids.length}</span>}</Link>
      <Link to="/cart" aria-label={`Cart with ${count} items`} className="relative flex items-end gap-1 rounded p-1 font-bold hover:bg-white/10"><ShoppingCart size={28}/><span className="hidden sm:inline">Cart</span>{count > 0 && <span className="absolute -right-2 -top-2 grid h-5 min-w-5 place-items-center rounded-full bg-amber-400 px-1 text-xs text-slate-950">{count}</span>}</Link>
    </div><form onSubmit={search} className="mx-4 mb-3 flex overflow-hidden rounded-lg bg-white sm:hidden"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search SokoStyle" className="min-w-0 flex-1 px-4 py-2 text-sm text-slate-900 outline-none"/><button className="bg-amber-400 px-4 text-slate-900" aria-label="Search"><Search size={19}/></button></form></div>
    <nav className="overflow-x-auto whitespace-nowrap border-b bg-white"><div className="mx-auto flex max-w-7xl items-center gap-7 px-4 py-2.5 text-sm font-semibold text-slate-700"><button onClick={() => choose("All")}>All departments</button>{["Women","Men","Shoes","Kids","Accessories"].map((c) => <button key={c} onClick={() => choose(c)}>{c}</button>)}<button onClick={() => choose("Deals")} className="text-rose-600">Today’s deals</button><button onClick={() => choose("New")}>New arrivals</button><a href="mailto:sellers@sokostyle.co.tz?subject=Sell on SokoStyle">Sell on SokoStyle</a></div></nav>
    {menuOpen && <div className="fixed inset-0 z-[60] bg-slate-950/50 md:hidden" onClick={() => setMenuOpen(false)}><aside className="h-full w-[82%] max-w-xs bg-white p-5 text-slate-900 shadow-2xl" onClick={(e) => e.stopPropagation()}><div className="flex items-center justify-between"><b className="text-xl">Browse SokoStyle</b><button onClick={() => setMenuOpen(false)} aria-label="Close menu" className="rounded p-2 hover:bg-slate-100"><X/></button></div><div className="mt-6 grid gap-1">{departments.map((item) => <button key={item} onClick={() => choose(item)} className="rounded-lg px-3 py-3 text-left font-semibold hover:bg-emerald-50 hover:text-emerald-700">{item === "All" ? "All departments" : item}</button>)}<button onClick={() => choose("Deals")} className="rounded-lg px-3 py-3 text-left font-semibold text-rose-600 hover:bg-rose-50">Today’s deals</button><button onClick={() => choose("New")} className="rounded-lg px-3 py-3 text-left font-semibold hover:bg-emerald-50">New arrivals</button><Link to="/wishlist" onClick={() => setMenuOpen(false)} className="rounded-lg px-3 py-3 font-semibold hover:bg-emerald-50">Wishlist ({wishlist.ids.length})</Link></div></aside></div>}
  </header>;
}

export function SiteFooter() { const help = (message: string) => toast.info(message); return <footer className="mt-16 bg-slate-950 text-slate-300"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-12 sm:grid-cols-2 lg:grid-cols-4"><div><Link to="/" className="text-2xl font-black text-white">soko<span className="text-amber-300">style</span></Link><p className="mt-3 text-sm leading-6">Tanzania’s easy fashion marketplace. Great style, trusted sellers and delivery from Dar to every region.</p></div><div><h3 className="font-bold text-white">Shop</h3><div className="mt-3 grid justify-start gap-2 text-sm">{["Women","Men","Kids","Shoes","Accessories"].map((c) => <Link key={c} to="/" search={{category:c}} className="hover:text-white">{c === "Shoes" ? "Shoes & sandals" : c}</Link>)}</div></div><div><h3 className="font-bold text-white">Customer care</h3><div className="mt-3 grid justify-start gap-2 text-left text-sm"><button onClick={() => help("Order tracking will appear after you place an order.")}>Track your order</button><button onClick={() => help("Items can be returned within 7 days if unworn and in original condition.")}>Returns & refunds</button><button onClick={() => help("Delivery takes 1–2 days in Dar and 2–5 days in other regions.")}>Delivery information</button><a href="mailto:support@sokostyle.co.tz">Contact us</a></div></div><div><h3 className="font-bold text-white">Pay safely</h3><p className="mt-3 text-sm leading-7">M-Pesa · Airtel Money<br/>Mixx by Yas · HaloPesa<br/>Visa · Mastercard · Cash</p></div></div><div className="border-t border-white/10 px-5 py-5 text-center text-xs">© 2026 SokoStyle Tanzania · Bei nzuri. Mtindo wako.</div></footer>; }
